version: "3.9"
services:
  app:
    build: ./docker
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      - db
      - minio
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: botc
      POSTGRES_USER: botc
      POSTGRES_PASSWORD: botc
    volumes:
      - db_data:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
volumes:
  db_data:
  minio_data:
