CREATE TABLE IF NOT EXISTS "LikeEvent" (
  "id" TEXT PRIMARY KEY,
  "scriptId" TEXT NOT NULL,
  "actorId" TEXT,
  "createdAt" DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("scriptId") REFERENCES "Script"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS "Favorite" (
  "id" TEXT PRIMARY KEY,
  "scriptId" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "createdAt" DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE("scriptId","userId"),
  FOREIGN KEY ("scriptId") REFERENCES "Script"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

