name: Lighthouse CI

on:
  pull_request:
    branches: [master, main]
  push:
    branches: [master, main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          DATABASE_URL: file:./test.db
          NEXTAUTH_SECRET: test-secret-for-ci

      - name: Start server
        run: npm run start &
        env:
          DATABASE_URL: file:./test.db
          NEXTAUTH_SECRET: test-secret-for-ci
          PORT: 3000

      - name: Wait for server
        run: npx wait-on http://localhost:3000 -t 60000

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI
        run: lhci autorun

      - name: Upload results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-results
          path: .lighthouseci

